# Generated by Django 4.2.5 on 2023-10-08 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_drivermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivermodel',
            name='ridetype',
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=50)),
                ('citizenship_photo', models.ImageField(upload_to='documents/')),
                ('phone_number', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='drivermodel',
            name='rideType',
            field=models.CharField(default='bike', max_length=20),
        ),
    ]
