# Generated by Django 4.2.5 on 2023-10-09 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_verification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='drivername',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
