# Generated by Django 4.2.5 on 2023-10-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_drivermodel_drivername_alter_verification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivermodel',
            old_name='passenger',
            new_name='seats',
        ),
    ]
