# Generated by Django 4.2.5 on 2023-10-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clientmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='rideType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
