# Generated by Django 4.2.5 on 2023-10-15 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_clientmodel_date_alter_clientmodel_ridetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('rideType', models.CharField(blank=True, max_length=20, null=True)),
                ('passenger', models.IntegerField(blank=True, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('clientname', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
                ('drivername', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='drivermodel',
            name='drivername',
        ),
        migrations.DeleteModel(
            name='ClientModel',
        ),
        migrations.DeleteModel(
            name='DriverModel',
        ),
    ]
