# Generated by Django 4.2.5 on 2023-10-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_ridemodel_remove_drivermodel_drivername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridemodel',
            name='accept',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
