# Generated by Django 4.2.5 on 2023-11-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_ridemodel_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridemodel',
            name='accept',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
