# Generated by Django 4.2.5 on 2023-12-03 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_contactusmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
