# Generated by Django 4.2.5 on 2023-12-03 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_contactusmodel_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridemodel',
            name='clientname',
        ),
        migrations.AddField(
            model_name='ridemodel',
            name='clientname',
            field=models.ManyToManyField(blank=True, null=True, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
