# Generated by Django 4.2.5 on 2023-12-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_ridemodel_clientname_ridemodel_clientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridemodel',
            name='passenger',
        ),
    ]
