# Generated by Django 4.2.5 on 2023-12-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_ridemodel_rent_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridemodel',
            name='clientname',
        ),
    ]
