# Generated by Django 4.2.5 on 2023-12-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_ridemodel_clientname'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rent',
            field=models.CharField(default='333', max_length=5),
            preserve_default=False,
        ),
    ]
