# Generated by Django 4.2.5 on 2023-12-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rent_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='user',
            new_name='user_client',
        ),
    ]
