# Generated by Django 4.2.5 on 2023-12-03 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_user_rent_user_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='user_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to=settings.AUTH_USER_MODEL),
        ),
    ]
