# Generated by Django 4.2.5 on 2023-12-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_rent_user_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridemodel',
            name='accept',
        ),
        migrations.AddField(
            model_name='rent',
            name='requestAccept',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
