# Generated by Django 4.2.5 on 2023-12-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_rent_requestaccept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='requestAccept',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
