# Generated by Django 4.2.5 on 2023-12-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_rent_created_on_ridemodel_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
