# Generated by Django 4.2.5 on 2023-12-11 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='driver_doc')),
                ('license', models.ImageField(upload_to='driver_doc')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
